# Generated by Django 5.1.4 on 2025-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects_table',
        ),
    ]
