# Generated by Django 5.1.4 on 2025-01-15 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_alter_task_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
