# Generated by Django 5.1.4 on 2025-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_task_task_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_create',
            field=models.DateField(),
        ),
    ]
