# Generated by Django 5.1.4 on 2025-01-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_phone', models.IntegerField(max_length=9, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(max_length=100)),
                ('user_status', models.IntegerField(default=1)),
            ],
        ),
    ]
