# Generated by Django 5.1.4 on 2025-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.IntegerField(unique=True),
        ),
    ]
