# Generated by Django 5.1.4 on 2025-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_user_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
