# Generated by Django 5.1.4 on 2025-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_rut',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
