# Generated by Django 5.1.4 on 2025-01-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('DEV', 'Desarrollador'), ('QA', 'Quality Assurance'), ('PM', 'Project Manager'), ('UX', 'Diseñador de Experiencia de Usuario'), ('UI', 'Diseñador de Interfaz de Usuario'), ('PO', 'Product Owner'), ('BA', 'Business Analyst'), ('CTO', 'Chief Technology Officer'), ('CEO', 'Chief Executive Officer'), ('COO', 'Chief Operating Officer'), ('HR', 'Recursos Humanos'), ('SM', 'Scrum Master'), ('DEVOPS', 'Ingeniero DevOps'), ('SYS_ADMIN', 'Administrador de Sistemas'), ('DBA', 'Administrador de Base de Datos'), ('FRONTEND', 'Desarrollador Frontend'), ('BACKEND', 'Desarrollador Backend'), ('FULLSTACK', 'Desarrollador Fullstack'), ('DS', 'Científico de Datos'), ('DE', 'Ingeniero de Datos'), ('ML', 'Ingeniero de Machine Learning'), ('SUPPORT', 'Soporte Técnico'), ('SECURITY', 'Especialista en Seguridad'), ('MARKETING', 'Marketing'), ('SALES', 'Ventas'), ('CS', 'Éxito del Cliente'), ('NS', 'No seleccionado')], default='NS', max_length=100),
        ),
    ]
