# Generated by Django 5.1.4 on 2025-01-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_user_user_password_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$vsN9X9sSx7BLrZWYzqgVXW$WEtUS/daXXodZwTSt//Da2vozn6sttoCaXpPq+acd34=', max_length=128),
        ),
    ]
