# Generated by Django 5.1.4 on 2025-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='userImages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$PZIURUL7ztugIdG1zIQ7cg$FARF37X819BqnrD/ZAVzBPBaK6HEuI76ShLKKBMj6M4=', max_length=128),
        ),
    ]
