# Generated by Django 5.1.4 on 2025-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_user_user_image_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jcbgBXAVumu2R565RD0wkL$1ES2onmT3SwhnZlP5klg0ea7MxK3dm0y6O7N95XaUME=', max_length=128),
        ),
    ]
