# Generated by Django 5.1.4 on 2025-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$VmlVuiESZQSX0XWH4Ys7JG$ft/bY22+AudOXinSX+uUkfB1F4Y8sK7gUkkksrNifGU=', max_length=128),
        ),
    ]
