# Generated by Django 5.1.4 on 2025-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$tnP3LBgjMTqW078HcAX5tZ$g3xLQKGldbPErMr6Uf8MF4I/oeNfuVcHdZm9nqG+tPE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='userImages'),
        ),
    ]
