# Generated by Django 5.1.4 on 2025-01-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0002_alter_project_table'),
        ('User', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_date_create', models.DateField(auto_now_add=True)),
                ('team_members', models.ManyToManyField(related_name='team_members', to='User.user')),
                ('team_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_project', to='Projects.project')),
            ],
            options={
                'db_table': 'team_table',
            },
        ),
    ]
