# Generated by Django 5.1.4 on 2025-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTeams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteam',
            name='team_date_create',
            field=models.DateField(),
        ),
    ]
